### ISSUE TITLE
https://fchan.xyz/ is down?

### ISSUE THREAD

**Issue by narskidan** [FChannel0/Server#85]
Is this project still alive?

**Comment by ghost** [comment]
It's been dead for quite some time now. I'm *somewhat* continuing development of FChannel at <https://github.com/KushBlazingJudah/fedichan> however it's on hiatus due to time constraints currently and there's a lot I simply haven't gotten around to fixing yet.
The only remaining instance that I know of is <https://usagi.reisen>.

**Comment by cag143** [comment]
The main problem with gochan is that it is written in go, which is problematic in comparison to the clearly superior rust lang. There was a time, a blink of an eye, when people thought that golang was the top lang and had a massive future, then rust proved that go coders are the pre-preschoolers of coding. Not even preschoolers, the pre-preschoolers.

**Comment by aicynide** [comment]
@KushBlazingJudah why did you stop development?

**Comment by narskidan** [comment]
usagi.reisen seems pretty active - seems like the software works. I guess the maintainer just doesn't have free time to do this.
